services:
  database: 
    ports: !override
      - "5432:5432"
  webserver:
    ports: !override
      - "80:80"
  web:
    ports: !override
      - "3000:80"
  adminer:
    ports: !override
      - "8080:8080"