version: '3'

services:
  db:
    image: 'postgres:alpine'
    environment:
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootpassword
    ports:
      - 5436:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/var/www/html
    environment:
      SYMFONY_ENV: dev
      DATABASE_URL: postgresql://rootuser:rootpassword@db:5432/ecommerce
  web:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    environment:
      FLASK_ENV: development
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: