version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: ecommerce
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      SYMFONY_ENV: dev
  web:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: