version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POST_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      SYMFONY_ENV: dev
  web:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development

volumes:
  db-data: